import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import { AuthToastListener } from "@/components/auth-toast-listener"
import { ThemeProvider } from "@/components/theme-provider"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        {/* Bungkus aplikasi dengan ThemeProvider untuk support Dark Mode */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}

          {/* Suspense wajib digunakan karena AuthToastListener menggunakan useSearchParams */}
          <Suspense fallback={null}>
            <AuthToastListener />
          </Suspense>

          {/* Toaster dari Sonner untuk notifikasi alert */}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}