import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react"; // 1. Import Suspense
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import { AuthToastListener } from "@/components/auth-toast-listener"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}

        {/* 2. WRAP DENGAN SUSPENSE: Wajib untuk useSearchParams */}
        <Suspense fallback={null}>
          <AuthToastListener />
        </Suspense>

        <Toaster />
      </body>
    </html>
  );
}